bingoArr = [
    "1. Someone gets robbed",
    "2. Draw from the deck of many things",
    "3. The group gets a pet",
    "4. Win a mini game",
    "5. Critical Success",
    "6. Waterdeep Reference",
    "7. Botched an NPC conversation",
    "8. DM is not tech support",
    "9. Someone yells westside",
    "10. Erik makes a pun",
    "11. Cora accidently dms",
    "12. Calls NPC the wrong name",
    "13. Free Space",
    "14. Landry mentions killing a child",
    "15. Jacob tries to seduce someone",
    "16. The group adopts a NPC",
    "17. Ooga Balooga mention",
    "18. Critical Failure",
    "19. Lose a mini game",
    "20. Someone dies",
    "21. Janina flirts with a Himbo",
    "22. Nate hits on a milf",
    "23. Forgotten notes",
    "24. DM has to repeat",
    "25. Someone gets arrested"
]